### ISSUE TITLE
Could you please upload the TSV file from your test data for comparison?

### ISSUE THREAD

**Issue by FYF68** [y9c/m5C-UBSseq#2]
Hello, I used deduplicated BAM file to call mutation and obtained the following TSV file, but it appears some issues. Could you please upload the TSV file from your test data for comparison?
![8388b841f934866878b8b836e5ce7a4](https://github.com/y9c/m5C-UBSseq/assets/168499161/dd3d852d-c515-4ece-a817-cdee2605984c)

**Comment by y9c** [comment]
Hi, this file is in correct format, but the QC column is weird. This is relative to your fq file rather than the code. Could you show the fq file?

**Comment by FYF68** [comment]
Thank you for your response. The fastq files employed in my analysis were derived from your paper siControl HeLa polyA+RNA treated with ultrafast BS, replicate1 and 2 , obtained from the dataset GSE225614 hosted on the NCBI's Gene Expression Omnibus (GEO) under the accession [GSE225614](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?&acc=GSE225614).
![image](https://github.com/y9c/m5C-UBSseq/assets/168499161/90e9d0bf-031d-4ad4-9eca-dc68e9550fe3)

![1715063521884](https://github.com/y9c/m5C-UBSseq/assets/168499161/ced64bcb-8ffc-4bc2-a104-5f5cbb8cbf1d)

**Comment by y9c** [comment]
I understand now. It appears that you have made a mistake when downloading the fastq file from NCBI. The quality string is missing. You can download the data again and restart the analysis.

**Comment by FYF68** [comment]
Thank you!  I will try it again.
