### ISSUE TITLE
Any documentation available?

### ISSUE THREAD

**Issue by hengjwj** [y9c/m5C-UBSseq#4]
Hi! 

I'm not sure if I missed it but is there documentation regarding how to run this pipeline and customisation options somewhere?

Thanks!

Joel

**Comment by y9c** [comment]
Hi @hengjwj,

There is no document for this repo at this moment. I will be adding one. In the meantime, if you have any questions about how to use the code, feel free to ask. I will add them into the document accordingly.

**Comment by hengjwj** [comment]
Hi! 

My main concern is checking that everything is installed and runs as intended. Maybe as a start, could you share how the test data provided is intended to be run? I modified lines 3-9 in config.yaml to the paths of software I installed, but I'm not sure what versions will work. Do lines 11-20 need to modified? Additionally, what species' reference FASTA should I use for lines 25-32 in config.yaml?

**Comment by y9c** [comment]
Any bisulfite sequencing data will work. You can apply it to your own sequencing data. If not, you can download the from our previous publication. The species depend on the sample you sequenced. Please let me know if you have any questions.

**Comment by hengjwj** [comment]
Hi, thanks for the prompt response. I understand it's broadly applicable to BS-seq. My question is how can I tell whether the installation has no issues, and that it runs fine? If the test data provided in the repo has been processed before, then could you share the results of its analysis so I may see if the results generated using this pipeline in my environment can obtain the same results? Alternatively, besides reproducing your results, are there better ways of checking?
